# Generated by Django 3.2 on 2022-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(default='', max_length=32, verbose_name='项目名称')),
                ('it_desc', models.CharField(default='', max_length=255, verbose_name='项目描述')),
                ('it_start_time', models.DateField(verbose_name='项目开始时间')),
                ('it_end_time', models.DateField(verbose_name='项目结束时间')),
            ],
        ),
    ]
