# Generated by Django 3.2 on 2022-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it',
            name='it_desc',
            field=models.CharField(default='', max_length=256, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='it',
            name='it_name',
            field=models.CharField(default='', max_length=64, verbose_name='项目名称'),
        ),
    ]
