# Generated by Django 3.2 on 2022-07-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220624_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(default='', max_length=32, verbose_name='用例名称')),
                ('case_lv', models.CharField(default='', max_length=32, verbose_name='用例名称')),
            ],
        ),
    ]
