# Generated by Django 3.2 on 2022-10-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20220711_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_pass_status',
            field=models.IntegerField(choices=[(0, '未通过'), (1, '已通过')], verbose_name='执行是否通过'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_run_status',
            field=models.IntegerField(choices=[(0, '未执行'), (1, '已执行')], verbose_name='是否执行'),
        ),
    ]
