# Generated by Django 3.2 on 2022-10-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20221031_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_pass_status',
            field=models.IntegerField(choices=[(0, '未通过'), (1, '已通过')], default=0, verbose_name='执行是否通过'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_run_status',
            field=models.IntegerField(choices=[(0, '未执行'), (1, '已执行')], default=0, verbose_name='是否执行'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_run_time',
            field=models.DateTimeField(default='', null=True, verbose_name='执行时间'),
        ),
    ]
